begin;
select set_config('zenit_test.uid', gen_random_uuid()::text, true);
select set_config('zenit_test.other', gen_random_uuid()::text, true);
insert into auth.users(id) values (current_setting('zenit_test.uid')::uuid), (current_setting('zenit_test.other')::uuid);
set local role authenticated;
select set_config('request.jwt.claim.sub', current_setting('zenit_test.uid'), true);
select set_config('request.jwt.claims', '{}', true);
do $$
declare s jsonb := '{"kind":"monthly","timeZone":"America/Sao_Paulo","startAt":"2026-01-01T00:00:00Z","endAt":null,"times":["07:00"],"weekDays":[4],"monthDay":29,"intervalMinutes":720,"windowStart":null,"windowEnd":null}';
  doc jsonb; id uuid := gen_random_uuid(); op uuid := gen_random_uuid(); res jsonb; prev jsonb; next_at timestamptz; n integer; other_sid uuid := gen_random_uuid();
begin
  if public.zenit_day_next_reminder(s,'2026-02-01Z') <> '2026-02-28T10:00:00Z'::timestamptz then raise exception 'February clamp'; end if;
  if public.zenit_day_next_reminder(s,'2026-02-28T10:00:00Z') <> '2026-03-29T10:00:00Z'::timestamptz then raise exception 'Original month day lost'; end if;
  if public.zenit_day_next_reminder(s,'2028-02-01Z') <> '2028-02-29T10:00:00Z'::timestamptz then raise exception 'Leap February'; end if;
  if public.zenit_day_next_reminder(s || '{"monthDay":31}','2026-04-01Z') <> '2026-04-30T10:00:00Z'::timestamptz then raise exception 'April clamp'; end if;
  if public.zenit_day_next_reminder(s || '{"kind":"weekly"}','2026-10-02Z') <> '2026-10-08T10:00:00Z'::timestamptz then raise exception 'Weekly day'; end if;
  if public.zenit_day_next_reminder(s || '{"kind":"daily","times":["23:00","07:00","15:00"]}','2026-10-02T11:00:00Z') <> '2026-10-02T18:00:00Z'::timestamptz then raise exception 'Multiple daily times'; end if;
  s := s || '{"kind":"interval","startAt":"2026-10-02T10:00:00Z","endAt":"2026-10-09T10:00:00Z"}';
  next_at := '2026-10-02T09:59:59Z'; n := 0;
  loop
    next_at := public.zenit_day_next_reminder(s,next_at);
    exit when next_at is null;
    n := n+1;
    if n > 14 then raise exception 'Exclusive end exceeded'; end if;
  end loop;
  if n <> 14 then raise exception '12 hours for 7 days'; end if;
  if public.zenit_day_next_reminder(s,'2026-10-02T10:12:00Z') <> '2026-10-02T22:00:00Z'::timestamptz then raise exception 'Interval drift'; end if;
  s := s || '{"intervalMinutes":120,"windowStart":"08:00","windowEnd":"18:00","endAt":null}';
  if public.zenit_day_next_reminder(s,'2026-10-02T20:00:00Z') <> '2026-10-02T21:00:00Z'::timestamptz then raise exception 'Daily window end'; end if;
  if public.zenit_day_next_reminder(s,'2026-10-02T21:00:00Z') <> '2026-10-03T11:00:00Z'::timestamptz then raise exception 'Daily window reset'; end if;
  begin perform public.zenit_day_next_reminder(s || '{"times":["155:00"]}',now()); raise exception 'Invalid time accepted'; exception when invalid_parameter_value then null; end;
  begin perform public.zenit_day_next_reminder(s || '{"intervalMinutes":0}',now()); raise exception 'Invalid interval accepted'; exception when invalid_parameter_value then null; end;
  doc := jsonb_build_object('title','Lembrete de teste','subject_id',null,'enabled',true,'deleted',false,'schedule',s);
  res := public.zenit_day_save_reminder(op,id,0,doc);
  if res->>'result' <> 'saved' or (res->'reminder'->>'revision')::int <> 1 then raise exception 'Create failed'; end if;
  if public.zenit_day_save_reminder(op,id,0,doc) <> res then raise exception 'Duplicate request differs'; end if;
  begin perform public.zenit_day_save_reminder(op,id,0,doc || '{"title":"Altered"}'); raise exception 'Operation reuse accepted'; exception when invalid_parameter_value then null; end;
  if public.zenit_day_save_reminder(gen_random_uuid(),id,0,doc)->>'result' <> 'conflict' then raise exception 'Lost update'; end if;
  res := public.zenit_day_save_reminder(gen_random_uuid(),id,1,doc || '{"enabled":false}');
  if res->'reminder'->>'enabled' <> 'false' then raise exception 'Pause failed'; end if;
  perform set_config('request.jwt.claims','{"client_id":"hub-client"}',true);
  select count(*) into n from public.zenit_day_reminders;
  if n <> 0 then raise exception 'Existing OAuth grant must not expand'; end if;
  begin perform public.zenit_day_save_reminder(gen_random_uuid(),id,2,doc); raise exception 'OAuth wrote'; exception when insufficient_privilege then null; end;
  perform set_config('request.jwt.claims','{}',true);
  perform set_config('request.jwt.claim.sub',current_setting('zenit_test.other'),true);
  select count(*) into n from public.zenit_day_reminders;
  if n <> 0 then raise exception 'Cross-account disclosure'; end if;
  res := public.zenit_day_save_reminder(gen_random_uuid(),id,2,doc);
  if res->>'result' <> 'conflict' or res->'reminder' <> 'null'::jsonb then raise exception 'Cross-account write'; end if;
  perform public.zenit_day_save_subject(gen_random_uuid(),other_sid,0,'{"title":"Other subject","status":"todo","responsible_is_self":true,"archived":false}');
  perform set_config('request.jwt.claim.sub',current_setting('zenit_test.uid'),true);
  begin perform public.zenit_day_save_reminder(gen_random_uuid(),id,2,doc || jsonb_build_object('subject_id',other_sid)); raise exception 'Foreign subject linked'; exception when foreign_key_violation then null; end;
  res := public.zenit_day_save_reminder(gen_random_uuid(),id,2,doc || '{"enabled":false,"deleted":true}');
  if res->'reminder'->>'deleted' <> 'true' then raise exception 'Delete failed'; end if;
  begin update public.zenit_day_reminders set title='Bypass'; raise exception 'Direct write accepted'; exception when insufficient_privilege then null; end;
end $$;
set local role anon;
do $$ begin
  begin perform public.zenit_day_save_reminder(gen_random_uuid(),gen_random_uuid(),0,'{}'); raise exception 'Anon mutation'; exception when insufficient_privilege then null; end;
  begin perform count(*) from public.zenit_day_reminders; raise exception 'Anon read'; exception when insufficient_privilege then null; end;
end $$;
rollback;
select 'Reminder recurrence, idempotency, conflicts, owner isolation and OAuth boundaries passed' as result;
